plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hororindonesia'
    compileSdk 34

    defaultConfig {
        applicationId "com.hororindonesia"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    aaptOptions {
        noCompress 'html', 'js', 'css', 'png', 'jpg', 'json'
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.9.0'
}